export const APP_LINKS = {
  "website": 'http://localhost:3000',
  "easycook": 'http://localhost:3001',
  "snugglefox": 'http://localhost:3002',
  "gst-calculator": 'http://localhost:3003',
  "one-page-invoice": 'http://localhost:3004',
  "gst-whatsapp-biller": 'http://localhost:3005',
  "follow-up-fox": 'http://localhost:3006',
  "trade-quote": 'http://localhost:3007',
  "proposal-forge": 'http://localhost:3008',
  "course-ship": 'http://localhost:3009',
  "member-gate": 'http://localhost:3010',
  "margin-lens": 'http://localhost:3011',
  "etsy-ledger": 'http://localhost:3012',
  "rent-ledger": 'http://localhost:3013',
  "stock-sentinel": 'http://localhost:3014',
  "ship-watch": 'http://localhost:3015',
  "uptime-peek": 'http://localhost:3016',
  "nudge-book": 'http://localhost:3017',
  "quote-card": 'http://localhost:3018',
  "testimonial-jar": 'http://localhost:3019',
  "review-radar": 'http://localhost:3020',
  "report-snap": 'http://localhost:3021',
  "doc-chaser": 'http://localhost:3022',
  "scope-guard": 'http://localhost:3023',
  "tiny-crm": 'http://localhost:3024',
  "crew-board": 'http://localhost:3025',
} as const

export type AppSlug = keyof typeof APP_LINKS
