import type { Meal } from './types'

export const MEAL_DATABASE: Meal[] = [
  // ── BREAKFASTS ──────────────────────────────────────────────
  {
    id: 'b-oats-banana',
    name: 'Banana Oat Porridge',
    type: 'breakfast',
    cuisine: 'American',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    description: 'Creamy oats with caramelised banana and a drizzle of honey',
    spiceLevel: 1,
    allergens: ['Gluten'],
    healthGoals: ['weight-loss', 'balanced', 'heart-healthy'],
    nutrition: {
      macros: { calories: 320, protein: 10, carbs: 58, fat: 6, fiber: 6, sugar: 18 },
      micros: { vitaminC: 8, potassium: 420, magnesium: 52, iron: 2.2, calcium: 140, folate: 22, omega3: 60 },
    },
    ingredients: [
      { name: 'Rolled oats', quantity: '1', unit: 'cup', category: 'grains-legumes' },
      { name: 'Banana', quantity: '1', unit: 'large', category: 'produce' },
      { name: 'Milk', quantity: '1.5', unit: 'cups', category: 'dairy' },
      { name: 'Honey', quantity: '1', unit: 'tbsp', category: 'other' },
      { name: 'Cinnamon', quantity: '0.5', unit: 'tsp', category: 'spices-condiments' },
    ],
  },
  {
    id: 'b-avocado-toast',
    name: 'Avocado Toast with Poached Eggs',
    type: 'breakfast',
    cuisine: 'American',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    description: 'Creamy avocado on sourdough with perfectly poached eggs and chilli flakes',
    spiceLevel: 2,
    allergens: ['Gluten', 'Eggs'],
    healthGoals: ['balanced', 'high-protein', 'heart-healthy'],
    nutrition: {
      macros: { calories: 420, protein: 18, carbs: 32, fat: 26, fiber: 8, sugar: 3 },
      micros: { vitaminA: 120, vitaminC: 12, vitaminD: 1.8, vitaminB12: 0.8, iron: 2.8, calcium: 90, potassium: 680, sodium: 340, zinc: 1.8, folate: 110, omega3: 180 },
    },
    ingredients: [
      { name: 'Sourdough bread', quantity: '4', unit: 'slices', category: 'grains-legumes' },
      { name: 'Avocado', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Eggs', quantity: '4', unit: 'large', category: 'dairy' },
      { name: 'Lemon juice', quantity: '1', unit: 'tbsp', category: 'produce' },
      { name: 'Chilli flakes', quantity: '0.5', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Salt', quantity: 'to taste', unit: '', category: 'spices-condiments' },
    ],
  },
  {
    id: 'b-masala-omelette',
    name: 'Masala Omelette',
    type: 'breakfast',
    cuisine: 'Indian',
    dietTypes: ['veg', 'eggetarian', 'pescatarian', 'non-veg'],
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    description: 'Fluffy Indian-spiced omelette with onions, tomatoes, and green chillies',
    spiceLevel: 3,
    allergens: ['Eggs'],
    healthGoals: ['high-protein', 'balanced', 'muscle-gain'],
    nutrition: {
      macros: { calories: 280, protein: 22, carbs: 8, fat: 18, fiber: 1.5, sugar: 4 },
      micros: { vitaminA: 220, vitaminC: 18, vitaminD: 2.0, vitaminB12: 1.2, iron: 3.0, calcium: 80, potassium: 320, sodium: 460, zinc: 2.2, folate: 80, omega3: 200 },
    },
    ingredients: [
      { name: 'Eggs', quantity: '4', unit: 'large', category: 'dairy' },
      { name: 'Onion', quantity: '1', unit: 'small', category: 'produce' },
      { name: 'Tomato', quantity: '1', unit: 'medium', category: 'produce' },
      { name: 'Green chillies', quantity: '2', unit: '', category: 'produce' },
      { name: 'Coriander leaves', quantity: '2', unit: 'tbsp', category: 'produce' },
      { name: 'Cumin seeds', quantity: '0.5', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Butter', quantity: '1', unit: 'tbsp', category: 'dairy' },
    ],
  },
  {
    id: 'b-idli-sambar',
    name: 'Idli with Sambar',
    type: 'breakfast',
    cuisine: 'Indian',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    description: 'Soft steamed rice cakes served with tangy lentil sambar and coconut chutney',
    spiceLevel: 2,
    allergens: [],
    healthGoals: ['weight-loss', 'balanced', 'heart-healthy'],
    nutrition: {
      macros: { calories: 260, protein: 9, carbs: 50, fat: 3, fiber: 5, sugar: 4 },
      micros: { vitaminC: 10, iron: 2.8, calcium: 40, potassium: 360, magnesium: 44, folate: 68, sodium: 380 },
    },
    ingredients: [
      { name: 'Idli batter', quantity: '3', unit: 'cups', category: 'grains-legumes' },
      { name: 'Toor dal', quantity: '0.5', unit: 'cup', category: 'grains-legumes' },
      { name: 'Mixed vegetables', quantity: '1', unit: 'cup', category: 'produce' },
      { name: 'Tamarind paste', quantity: '1', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'Sambar powder', quantity: '2', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Mustard seeds', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Curry leaves', quantity: '10', unit: '', category: 'produce' },
    ],
  },
  {
    id: 'b-greek-yogurt',
    name: 'Greek Yogurt Parfait',
    type: 'breakfast',
    cuisine: 'Greek',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    description: 'Thick Greek yogurt layered with granola, mixed berries, and honey',
    spiceLevel: 1,
    allergens: ['Gluten', 'Dairy', 'Nuts'],
    healthGoals: ['balanced', 'high-protein', 'weight-loss'],
    nutrition: {
      macros: { calories: 380, protein: 20, carbs: 44, fat: 12, fiber: 4, sugar: 22 },
      micros: { vitaminA: 40, vitaminC: 22, vitaminD: 0.4, vitaminB12: 1.0, iron: 1.6, calcium: 280, potassium: 440, sodium: 80, zinc: 1.4, folate: 24, omega3: 100 },
    },
    ingredients: [
      { name: 'Greek yogurt', quantity: '2', unit: 'cups', category: 'dairy' },
      { name: 'Granola', quantity: '0.5', unit: 'cup', category: 'grains-legumes' },
      { name: 'Mixed berries', quantity: '1', unit: 'cup', category: 'produce' },
      { name: 'Honey', quantity: '2', unit: 'tbsp', category: 'other' },
      { name: 'Chia seeds', quantity: '1', unit: 'tbsp', category: 'other' },
    ],
  },
  {
    id: 'b-poha',
    name: 'Poha',
    type: 'breakfast',
    cuisine: 'Indian',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 5,
    cookTime: 12,
    servings: 3,
    description: 'Flattened rice with turmeric, peanuts, peas, and fresh coriander',
    spiceLevel: 2,
    allergens: ['Nuts'],
    healthGoals: ['weight-loss', 'balanced'],
    nutrition: {
      macros: { calories: 290, protein: 8, carbs: 52, fat: 7, fiber: 3, sugar: 2 },
      micros: { vitaminC: 8, iron: 2.0, calcium: 30, potassium: 280, magnesium: 38, folate: 44, sodium: 220 },
    },
    ingredients: [
      { name: 'Flattened rice (poha)', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Onion', quantity: '1', unit: 'medium', category: 'produce' },
      { name: 'Peas', quantity: '0.5', unit: 'cup', category: 'produce' },
      { name: 'Peanuts', quantity: '3', unit: 'tbsp', category: 'other' },
      { name: 'Mustard seeds', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Turmeric', quantity: '0.5', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Curry leaves', quantity: '8', unit: '', category: 'produce' },
      { name: 'Oil', quantity: '2', unit: 'tbsp', category: 'oils-fats' },
    ],
  },
  {
    id: 'b-smoothie-bowl',
    name: 'Tropical Smoothie Bowl',
    type: 'breakfast',
    cuisine: 'American',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    description: 'Blended mango-pineapple base topped with coconut, seeds, and fresh fruit',
    spiceLevel: 1,
    allergens: ['Nuts'],
    healthGoals: ['weight-loss', 'balanced', 'heart-healthy'],
    nutrition: {
      macros: { calories: 340, protein: 8, carbs: 62, fat: 8, fiber: 7, sugar: 38 },
      micros: { vitaminA: 180, vitaminC: 80, vitaminD: 0, iron: 1.4, calcium: 60, potassium: 580, magnesium: 48, folate: 36, omega3: 1200 },
    },
    ingredients: [
      { name: 'Frozen mango', quantity: '2', unit: 'cups', category: 'frozen' },
      { name: 'Pineapple', quantity: '0.5', unit: 'cup', category: 'produce' },
      { name: 'Coconut milk', quantity: '0.5', unit: 'cup', category: 'canned' },
      { name: 'Banana', quantity: '1', unit: '', category: 'produce' },
      { name: 'Granola', quantity: '0.25', unit: 'cup', category: 'grains-legumes' },
      { name: 'Coconut flakes', quantity: '2', unit: 'tbsp', category: 'other' },
      { name: 'Chia seeds', quantity: '1', unit: 'tsp', category: 'other' },
    ],
  },
  {
    id: 'b-upma',
    name: 'Vegetable Upma',
    type: 'breakfast',
    cuisine: 'Indian',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 5,
    cookTime: 15,
    servings: 3,
    description: 'Semolina porridge with sautéed vegetables, tempered with mustard seeds and curry leaves',
    spiceLevel: 2,
    allergens: ['Gluten'],
    healthGoals: ['balanced', 'weight-loss'],
    nutrition: {
      macros: { calories: 270, protein: 7, carbs: 48, fat: 6, fiber: 3, sugar: 3 },
      micros: { vitaminC: 12, iron: 1.8, calcium: 28, potassium: 300, magnesium: 32, folate: 36, sodium: 310 },
    },
    ingredients: [
      { name: 'Semolina (rava)', quantity: '1.5', unit: 'cups', category: 'grains-legumes' },
      { name: 'Mixed vegetables', quantity: '1', unit: 'cup', category: 'produce' },
      { name: 'Onion', quantity: '1', unit: 'medium', category: 'produce' },
      { name: 'Green chillies', quantity: '2', unit: '', category: 'produce' },
      { name: 'Mustard seeds', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Cashews', quantity: '2', unit: 'tbsp', category: 'other' },
      { name: 'Oil', quantity: '2', unit: 'tbsp', category: 'oils-fats' },
    ],
  },
  {
    id: 'b-pancakes',
    name: 'Fluffy Buttermilk Pancakes',
    type: 'breakfast',
    cuisine: 'American',
    dietTypes: ['veg', 'eggetarian'],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    description: 'Golden, fluffy pancakes served with maple syrup and fresh berries',
    spiceLevel: 1,
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    healthGoals: ['balanced'],
    nutrition: {
      macros: { calories: 420, protein: 12, carbs: 68, fat: 12, fiber: 2, sugar: 18 },
      micros: { vitaminA: 80, vitaminD: 1.0, vitaminB12: 0.6, iron: 2.4, calcium: 180, potassium: 240, sodium: 480, folate: 60 },
    },
    ingredients: [
      { name: 'All-purpose flour', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Buttermilk', quantity: '1.5', unit: 'cups', category: 'dairy' },
      { name: 'Eggs', quantity: '2', unit: '', category: 'dairy' },
      { name: 'Butter', quantity: '3', unit: 'tbsp', category: 'dairy' },
      { name: 'Baking powder', quantity: '2', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Sugar', quantity: '2', unit: 'tbsp', category: 'other' },
      { name: 'Maple syrup', quantity: '0.25', unit: 'cup', category: 'other' },
    ],
  },

  // ── LUNCHES ─────────────────────────────────────────────────
  {
    id: 'l-dal-rice',
    name: 'Dal Tadka with Steamed Rice',
    type: 'lunch',
    cuisine: 'Indian',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    description: 'Yellow lentils tempered with ghee, cumin, and garlic served with fluffy basmati rice',
    spiceLevel: 2,
    allergens: [],
    healthGoals: ['balanced', 'weight-loss', 'heart-healthy'],
    nutrition: {
      macros: { calories: 460, protein: 18, carbs: 82, fat: 8, fiber: 12, sugar: 4 },
      micros: { vitaminC: 6, iron: 4.8, calcium: 60, potassium: 640, magnesium: 72, folate: 160, sodium: 420, zinc: 2.4 },
    },
    ingredients: [
      { name: 'Yellow toor dal', quantity: '1', unit: 'cup', category: 'grains-legumes' },
      { name: 'Basmati rice', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Onion', quantity: '1', unit: 'large', category: 'produce' },
      { name: 'Tomatoes', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Garlic', quantity: '4', unit: 'cloves', category: 'produce' },
      { name: 'Ginger', quantity: '1', unit: 'inch', category: 'produce' },
      { name: 'Ghee', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { name: 'Cumin seeds', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Turmeric', quantity: '0.5', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Red chilli powder', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
    ],
  },
  {
    id: 'l-chicken-curry',
    name: 'Butter Chicken Curry',
    type: 'lunch',
    cuisine: 'Indian',
    dietTypes: ['non-veg', 'pescatarian'],
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    description: 'Tender chicken in a rich, creamy tomato-based sauce with fragrant spices',
    spiceLevel: 3,
    allergens: ['Dairy'],
    healthGoals: ['high-protein', 'muscle-gain', 'balanced'],
    nutrition: {
      macros: { calories: 520, protein: 38, carbs: 18, fat: 32, fiber: 3, sugar: 8 },
      micros: { vitaminA: 260, vitaminC: 22, vitaminD: 0.4, vitaminB12: 0.6, iron: 2.4, calcium: 120, potassium: 680, sodium: 620, zinc: 3.2, folate: 28, omega3: 80 },
    },
    ingredients: [
      { name: 'Chicken breast', quantity: '600', unit: 'g', category: 'meat-seafood' },
      { name: 'Tomatoes', quantity: '4', unit: 'large', category: 'produce' },
      { name: 'Onion', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Heavy cream', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { name: 'Butter', quantity: '3', unit: 'tbsp', category: 'dairy' },
      { name: 'Garam masala', quantity: '1.5', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Cumin', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Coriander powder', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Kasuri methi', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
    ],
  },
  {
    id: 'l-pasta-arrabbiata',
    name: 'Pasta Arrabbiata',
    type: 'lunch',
    cuisine: 'Italian',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    description: 'Penne in a fiery tomato sauce with garlic, chilli, and fresh basil',
    spiceLevel: 3,
    allergens: ['Gluten'],
    healthGoals: ['balanced', 'heart-healthy'],
    nutrition: {
      macros: { calories: 480, protein: 14, carbs: 78, fat: 12, fiber: 5, sugar: 8 },
      micros: { vitaminA: 120, vitaminC: 28, vitaminD: 0, iron: 3.6, calcium: 100, potassium: 560, sodium: 420, folate: 80, omega3: 40 },
    },
    ingredients: [
      { name: 'Penne pasta', quantity: '400', unit: 'g', category: 'grains-legumes' },
      { name: 'Canned tomatoes', quantity: '800', unit: 'g', category: 'canned' },
      { name: 'Garlic', quantity: '6', unit: 'cloves', category: 'produce' },
      { name: 'Olive oil', quantity: '4', unit: 'tbsp', category: 'oils-fats' },
      { name: 'Dried chilli flakes', quantity: '1.5', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Fresh basil', quantity: '0.5', unit: 'cup', category: 'produce' },
      { name: 'Parmesan', quantity: '60', unit: 'g', category: 'dairy' },
    ],
  },
  {
    id: 'l-caesar-salad',
    name: 'Classic Caesar Salad',
    type: 'lunch',
    cuisine: 'American',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 15,
    cookTime: 5,
    servings: 2,
    description: 'Crisp romaine with house Caesar dressing, croutons, and shaved parmesan',
    spiceLevel: 1,
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    healthGoals: ['weight-loss', 'balanced'],
    nutrition: {
      macros: { calories: 380, protein: 12, carbs: 24, fat: 26, fiber: 4, sugar: 4 },
      micros: { vitaminA: 620, vitaminC: 40, vitaminD: 0.4, vitaminB12: 0.4, iron: 2.0, calcium: 260, potassium: 520, sodium: 780, zinc: 1.6, folate: 120 },
    },
    ingredients: [
      { name: 'Romaine lettuce', quantity: '2', unit: 'heads', category: 'produce' },
      { name: 'Parmesan', quantity: '60', unit: 'g', category: 'dairy' },
      { name: 'Sourdough bread', quantity: '2', unit: 'slices', category: 'grains-legumes' },
      { name: 'Caesar dressing', quantity: '4', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'Olive oil', quantity: '2', unit: 'tbsp', category: 'oils-fats' },
      { name: 'Black pepper', quantity: 'to taste', unit: '', category: 'spices-condiments' },
    ],
  },
  {
    id: 'l-rajma-chawal',
    name: 'Rajma Chawal',
    type: 'lunch',
    cuisine: 'Indian',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 10,
    cookTime: 45,
    servings: 4,
    description: 'Hearty kidney bean curry simmered in a spiced tomato-onion gravy with rice',
    spiceLevel: 3,
    allergens: [],
    healthGoals: ['balanced', 'high-protein', 'muscle-gain'],
    nutrition: {
      macros: { calories: 490, protein: 20, carbs: 86, fat: 6, fiber: 14, sugar: 6 },
      micros: { vitaminC: 12, iron: 5.2, calcium: 72, potassium: 820, magnesium: 84, folate: 180, sodium: 480, zinc: 2.8 },
    },
    ingredients: [
      { name: 'Kidney beans (rajma)', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Basmati rice', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Onions', quantity: '3', unit: 'medium', category: 'produce' },
      { name: 'Tomatoes', quantity: '4', unit: 'medium', category: 'produce' },
      { name: 'Ginger-garlic paste', quantity: '2', unit: 'tbsp', category: 'produce' },
      { name: 'Rajma masala', quantity: '2', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Oil', quantity: '3', unit: 'tbsp', category: 'oils-fats' },
    ],
  },
  {
    id: 'l-chicken-salad',
    name: 'Grilled Chicken Salad',
    type: 'lunch',
    cuisine: 'Mediterranean',
    dietTypes: ['non-veg', 'pescatarian'],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    description: 'Grilled herb chicken over mixed greens with olives, feta, and lemon vinaigrette',
    spiceLevel: 2,
    allergens: ['Dairy'],
    healthGoals: ['high-protein', 'weight-loss', 'muscle-gain'],
    nutrition: {
      macros: { calories: 420, protein: 40, carbs: 12, fat: 24, fiber: 4, sugar: 6 },
      micros: { vitaminA: 520, vitaminC: 48, vitaminD: 0.2, vitaminB12: 0.4, iron: 2.6, calcium: 220, potassium: 740, sodium: 640, zinc: 3.8, folate: 80, omega3: 160 },
    },
    ingredients: [
      { name: 'Chicken breast', quantity: '400', unit: 'g', category: 'meat-seafood' },
      { name: 'Mixed salad greens', quantity: '200', unit: 'g', category: 'produce' },
      { name: 'Cherry tomatoes', quantity: '200', unit: 'g', category: 'produce' },
      { name: 'Feta cheese', quantity: '100', unit: 'g', category: 'dairy' },
      { name: 'Kalamata olives', quantity: '50', unit: 'g', category: 'other' },
      { name: 'Lemon', quantity: '1', unit: '', category: 'produce' },
      { name: 'Olive oil', quantity: '3', unit: 'tbsp', category: 'oils-fats' },
      { name: 'Oregano', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
    ],
  },
  {
    id: 'l-veg-biryani',
    name: 'Vegetable Biryani',
    type: 'lunch',
    cuisine: 'Indian',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 20,
    cookTime: 45,
    servings: 4,
    description: 'Fragrant basmati rice layered with spiced vegetables, saffron, and crispy onions',
    spiceLevel: 3,
    allergens: ['Dairy'],
    healthGoals: ['balanced'],
    nutrition: {
      macros: { calories: 520, protein: 12, carbs: 88, fat: 14, fiber: 6, sugar: 8 },
      micros: { vitaminA: 180, vitaminC: 24, vitaminD: 0.2, iron: 2.8, calcium: 100, potassium: 520, magnesium: 52, sodium: 560, folate: 72 },
    },
    ingredients: [
      { name: 'Basmati rice', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Mixed vegetables', quantity: '2', unit: 'cups', category: 'produce' },
      { name: 'Onions', quantity: '2', unit: 'large', category: 'produce' },
      { name: 'Yogurt', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { name: 'Saffron', quantity: '0.25', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Biryani masala', quantity: '2', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'Ghee', quantity: '3', unit: 'tbsp', category: 'dairy' },
      { name: 'Mint leaves', quantity: '0.25', unit: 'cup', category: 'produce' },
    ],
  },
  {
    id: 'l-chickpea-wrap',
    name: 'Spiced Chickpea Wrap',
    type: 'lunch',
    cuisine: 'Mediterranean',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    description: 'Crispy spiced chickpeas with hummus, roasted veggies, and tahini in a whole wheat wrap',
    spiceLevel: 2,
    allergens: ['Gluten', 'Sesame'],
    healthGoals: ['balanced', 'weight-loss', 'heart-healthy'],
    nutrition: {
      macros: { calories: 440, protein: 16, carbs: 64, fat: 14, fiber: 12, sugar: 6 },
      micros: { vitaminC: 60, vitaminA: 140, iron: 4.4, calcium: 120, potassium: 640, magnesium: 76, sodium: 520, zinc: 2.2, folate: 140 },
    },
    ingredients: [
      { name: 'Whole wheat wraps', quantity: '4', unit: '', category: 'grains-legumes' },
      { name: 'Chickpeas', quantity: '400', unit: 'g', category: 'canned' },
      { name: 'Hummus', quantity: '4', unit: 'tbsp', category: 'other' },
      { name: 'Bell peppers', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Cucumber', quantity: '1', unit: '', category: 'produce' },
      { name: 'Cumin', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Smoked paprika', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Tahini', quantity: '2', unit: 'tbsp', category: 'other' },
    ],
  },
  {
    id: 'l-fish-tacos',
    name: 'Baja Fish Tacos',
    type: 'lunch',
    cuisine: 'Mexican',
    dietTypes: ['non-veg', 'pescatarian'],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    description: 'Crispy battered fish with cabbage slaw, chipotle crema, and fresh lime in corn tortillas',
    spiceLevel: 3,
    allergens: ['Gluten', 'Fish', 'Dairy', 'Eggs'],
    healthGoals: ['balanced', 'high-protein'],
    nutrition: {
      macros: { calories: 480, protein: 30, carbs: 48, fat: 18, fiber: 5, sugar: 4 },
      micros: { vitaminA: 120, vitaminC: 32, vitaminD: 4.2, vitaminB12: 2.4, iron: 2.0, calcium: 140, potassium: 660, sodium: 580, zinc: 2.0, omega3: 1200 },
    },
    ingredients: [
      { name: 'White fish fillets (cod/tilapia)', quantity: '500', unit: 'g', category: 'meat-seafood' },
      { name: 'Corn tortillas', quantity: '12', unit: '', category: 'grains-legumes' },
      { name: 'Cabbage', quantity: '2', unit: 'cups', category: 'produce' },
      { name: 'Sour cream', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { name: 'Lime', quantity: '3', unit: '', category: 'produce' },
      { name: 'Chipotle sauce', quantity: '2', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'All-purpose flour', quantity: '1', unit: 'cup', category: 'grains-legumes' },
      { name: 'Oil', quantity: '0.5', unit: 'cup', category: 'oils-fats' },
    ],
  },

  // ── DINNERS ──────────────────────────────────────────────────
  {
    id: 'd-palak-paneer',
    name: 'Palak Paneer',
    type: 'dinner',
    cuisine: 'Indian',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    description: 'Cottage cheese cubes in a velvety spinach gravy with warm spices',
    spiceLevel: 2,
    allergens: ['Dairy'],
    healthGoals: ['balanced', 'high-protein', 'heart-healthy'],
    nutrition: {
      macros: { calories: 400, protein: 22, carbs: 18, fat: 28, fiber: 4, sugar: 5 },
      micros: { vitaminA: 1040, vitaminC: 52, vitaminD: 0.4, vitaminB12: 0.4, iron: 6.4, calcium: 480, potassium: 640, sodium: 520, zinc: 2.4, folate: 220, omega3: 80 },
    },
    ingredients: [
      { name: 'Paneer', quantity: '300', unit: 'g', category: 'dairy' },
      { name: 'Spinach', quantity: '500', unit: 'g', category: 'produce' },
      { name: 'Onion', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Tomatoes', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Garlic', quantity: '4', unit: 'cloves', category: 'produce' },
      { name: 'Ginger', quantity: '1', unit: 'inch', category: 'produce' },
      { name: 'Heavy cream', quantity: '3', unit: 'tbsp', category: 'dairy' },
      { name: 'Cumin seeds', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Garam masala', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
    ],
  },
  {
    id: 'd-grilled-salmon',
    name: 'Herb-Crusted Grilled Salmon',
    type: 'dinner',
    cuisine: 'Mediterranean',
    dietTypes: ['non-veg', 'pescatarian'],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    description: 'Salmon fillets with a lemon-herb crust, served with roasted asparagus and quinoa',
    spiceLevel: 1,
    allergens: ['Fish'],
    healthGoals: ['high-protein', 'heart-healthy', 'muscle-gain', 'weight-loss'],
    nutrition: {
      macros: { calories: 540, protein: 45, carbs: 32, fat: 26, fiber: 5, sugar: 3 },
      micros: { vitaminA: 180, vitaminC: 28, vitaminD: 14.0, vitaminB12: 4.8, iron: 3.2, calcium: 80, potassium: 980, sodium: 360, zinc: 2.8, folate: 80, omega3: 3800 },
    },
    ingredients: [
      { name: 'Salmon fillets', quantity: '600', unit: 'g', category: 'meat-seafood' },
      { name: 'Quinoa', quantity: '1', unit: 'cup', category: 'grains-legumes' },
      { name: 'Asparagus', quantity: '300', unit: 'g', category: 'produce' },
      { name: 'Lemon', quantity: '2', unit: '', category: 'produce' },
      { name: 'Fresh dill', quantity: '3', unit: 'tbsp', category: 'produce' },
      { name: 'Garlic', quantity: '3', unit: 'cloves', category: 'produce' },
      { name: 'Olive oil', quantity: '3', unit: 'tbsp', category: 'oils-fats' },
      { name: 'Dijon mustard', quantity: '2', unit: 'tbsp', category: 'spices-condiments' },
    ],
  },
  {
    id: 'd-pasta-carbonara',
    name: 'Pasta Carbonara',
    type: 'dinner',
    cuisine: 'Italian',
    dietTypes: ['eggetarian'],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    description: 'Silky pasta with a creamy egg and cheese sauce, crispy pancetta, and black pepper',
    spiceLevel: 1,
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    healthGoals: ['balanced', 'muscle-gain'],
    nutrition: {
      macros: { calories: 620, protein: 26, carbs: 68, fat: 28, fiber: 3, sugar: 3 },
      micros: { vitaminA: 120, vitaminD: 1.0, vitaminB12: 1.0, iron: 3.8, calcium: 280, potassium: 360, sodium: 680, zinc: 3.0, folate: 60, omega3: 80 },
    },
    ingredients: [
      { name: 'Spaghetti', quantity: '400', unit: 'g', category: 'grains-legumes' },
      { name: 'Eggs', quantity: '4', unit: 'large', category: 'dairy' },
      { name: 'Parmesan', quantity: '100', unit: 'g', category: 'dairy' },
      { name: 'Pancetta or bacon', quantity: '150', unit: 'g', category: 'meat-seafood' },
      { name: 'Garlic', quantity: '2', unit: 'cloves', category: 'produce' },
      { name: 'Black pepper', quantity: '2', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Olive oil', quantity: '2', unit: 'tbsp', category: 'oils-fats' },
    ],
  },
  {
    id: 'd-chicken-tikka-masala',
    name: 'Chicken Tikka Masala',
    type: 'dinner',
    cuisine: 'Indian',
    dietTypes: ['non-veg'],
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    description: 'Marinated tandoori chicken in a rich, spiced tomato-cream sauce',
    spiceLevel: 3,
    allergens: ['Dairy'],
    healthGoals: ['high-protein', 'muscle-gain', 'balanced'],
    nutrition: {
      macros: { calories: 560, protein: 42, carbs: 22, fat: 34, fiber: 4, sugar: 10 },
      micros: { vitaminA: 300, vitaminC: 28, vitaminD: 0.4, vitaminB12: 0.6, iron: 2.8, calcium: 160, potassium: 760, sodium: 680, zinc: 4.0, folate: 36, omega3: 80 },
    },
    ingredients: [
      { name: 'Chicken thighs', quantity: '700', unit: 'g', category: 'meat-seafood' },
      { name: 'Yogurt', quantity: '1', unit: 'cup', category: 'dairy' },
      { name: 'Canned tomatoes', quantity: '800', unit: 'g', category: 'canned' },
      { name: 'Heavy cream', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { name: 'Onion', quantity: '2', unit: 'large', category: 'produce' },
      { name: 'Ginger-garlic paste', quantity: '3', unit: 'tbsp', category: 'produce' },
      { name: 'Tikka masala paste', quantity: '3', unit: 'tbsp', category: 'spices-condiments' },
    ],
  },
  {
    id: 'd-stir-fry-tofu',
    name: 'Tofu & Vegetable Stir-Fry',
    type: 'dinner',
    cuisine: 'Chinese',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    description: 'Crispy tofu with colourful vegetables in a garlicky soy-ginger sauce over rice',
    spiceLevel: 2,
    allergens: ['Soy', 'Gluten', 'Sesame'],
    healthGoals: ['weight-loss', 'balanced', 'high-protein'],
    nutrition: {
      macros: { calories: 380, protein: 20, carbs: 48, fat: 12, fiber: 6, sugar: 8 },
      micros: { vitaminA: 360, vitaminC: 88, vitaminD: 0, vitaminB12: 0, iron: 5.2, calcium: 280, potassium: 640, sodium: 720, zinc: 2.4, folate: 96, omega3: 600 },
    },
    ingredients: [
      { name: 'Firm tofu', quantity: '400', unit: 'g', category: 'other' },
      { name: 'Jasmine rice', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Broccoli', quantity: '2', unit: 'cups', category: 'produce' },
      { name: 'Bell peppers', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Snap peas', quantity: '1', unit: 'cup', category: 'produce' },
      { name: 'Soy sauce', quantity: '3', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'Sesame oil', quantity: '1', unit: 'tbsp', category: 'oils-fats' },
      { name: 'Ginger', quantity: '1', unit: 'inch', category: 'produce' },
      { name: 'Garlic', quantity: '4', unit: 'cloves', category: 'produce' },
      { name: 'Cornstarch', quantity: '2', unit: 'tbsp', category: 'other' },
    ],
  },
  {
    id: 'd-mutton-rogan-josh',
    name: 'Mutton Rogan Josh',
    type: 'dinner',
    cuisine: 'Indian',
    dietTypes: ['non-veg'],
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    description: 'Slow-cooked Kashmiri lamb in aromatic whole spices with a deep red gravy',
    spiceLevel: 4,
    allergens: ['Dairy'],
    healthGoals: ['high-protein', 'muscle-gain'],
    nutrition: {
      macros: { calories: 580, protein: 44, carbs: 12, fat: 38, fiber: 2, sugar: 5 },
      micros: { vitaminA: 80, vitaminC: 8, vitaminD: 0, vitaminB12: 2.8, iron: 4.8, calcium: 100, potassium: 560, sodium: 540, zinc: 6.8, folate: 24, omega3: 200 },
    },
    ingredients: [
      { name: 'Mutton (bone-in)', quantity: '800', unit: 'g', category: 'meat-seafood' },
      { name: 'Yogurt', quantity: '1', unit: 'cup', category: 'dairy' },
      { name: 'Onions', quantity: '3', unit: 'large', category: 'produce' },
      { name: 'Kashmiri chilli powder', quantity: '2', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'Whole spices (cardamom, cloves, bay)', quantity: 'mix', unit: '', category: 'spices-condiments' },
      { name: 'Oil', quantity: '4', unit: 'tbsp', category: 'oils-fats' },
    ],
  },
  {
    id: 'd-vegan-buddha-bowl',
    name: 'Rainbow Buddha Bowl',
    type: 'dinner',
    cuisine: 'American',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    description: 'Roasted sweet potato, chickpeas, and quinoa with tahini dressing and greens',
    spiceLevel: 1,
    allergens: ['Sesame'],
    healthGoals: ['weight-loss', 'balanced', 'heart-healthy'],
    nutrition: {
      macros: { calories: 520, protein: 18, carbs: 72, fat: 18, fiber: 14, sugar: 12 },
      micros: { vitaminA: 1200, vitaminC: 60, vitaminD: 0, vitaminB12: 0, iron: 6.0, calcium: 120, potassium: 1020, magnesium: 120, sodium: 340, zinc: 3.2, folate: 200 },
    },
    ingredients: [
      { name: 'Quinoa', quantity: '1', unit: 'cup', category: 'grains-legumes' },
      { name: 'Sweet potato', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Chickpeas', quantity: '400', unit: 'g', category: 'canned' },
      { name: 'Kale', quantity: '2', unit: 'cups', category: 'produce' },
      { name: 'Red cabbage', quantity: '1', unit: 'cup', category: 'produce' },
      { name: 'Tahini', quantity: '3', unit: 'tbsp', category: 'other' },
      { name: 'Lemon', quantity: '1', unit: '', category: 'produce' },
      { name: 'Olive oil', quantity: '3', unit: 'tbsp', category: 'oils-fats' },
    ],
  },
  {
    id: 'd-prawn-curry',
    name: 'Coconut Prawn Curry',
    type: 'dinner',
    cuisine: 'Indian',
    dietTypes: ['non-veg', 'pescatarian'],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    description: 'Juicy prawns in a fragrant coconut milk curry with curry leaves and mustard seeds',
    spiceLevel: 3,
    allergens: ['Shellfish'],
    healthGoals: ['high-protein', 'balanced'],
    nutrition: {
      macros: { calories: 460, protein: 36, carbs: 16, fat: 28, fiber: 3, sugar: 6 },
      micros: { vitaminA: 160, vitaminC: 24, vitaminD: 4.0, vitaminB12: 2.2, iron: 4.2, calcium: 120, potassium: 680, sodium: 640, zinc: 3.6, omega3: 800 },
    },
    ingredients: [
      { name: 'Prawns', quantity: '500', unit: 'g', category: 'meat-seafood' },
      { name: 'Coconut milk', quantity: '400', unit: 'ml', category: 'canned' },
      { name: 'Onion', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Tomatoes', quantity: '2', unit: 'medium', category: 'produce' },
      { name: 'Coconut oil', quantity: '3', unit: 'tbsp', category: 'oils-fats' },
      { name: 'Curry leaves', quantity: '15', unit: '', category: 'produce' },
      { name: 'Mustard seeds', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Turmeric', quantity: '0.5', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Red chilli powder', quantity: '1.5', unit: 'tsp', category: 'spices-condiments' },
    ],
  },
  {
    id: 'd-mushroom-risotto',
    name: 'Wild Mushroom Risotto',
    type: 'dinner',
    cuisine: 'Italian',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    description: 'Creamy arborio rice with wild mushrooms, white wine, and parmesan',
    spiceLevel: 1,
    allergens: ['Dairy', 'Gluten'],
    healthGoals: ['balanced', 'heart-healthy'],
    nutrition: {
      macros: { calories: 520, protein: 14, carbs: 72, fat: 18, fiber: 4, sugar: 4 },
      micros: { vitaminA: 40, vitaminC: 8, vitaminD: 2.8, vitaminB12: 0.4, iron: 2.4, calcium: 240, potassium: 520, sodium: 580, zinc: 2.0, folate: 60, omega3: 40 },
    },
    ingredients: [
      { name: 'Arborio rice', quantity: '400', unit: 'g', category: 'grains-legumes' },
      { name: 'Mixed wild mushrooms', quantity: '400', unit: 'g', category: 'produce' },
      { name: 'Parmesan', quantity: '100', unit: 'g', category: 'dairy' },
      { name: 'White wine', quantity: '150', unit: 'ml', category: 'beverages' },
      { name: 'Vegetable stock', quantity: '1.5', unit: 'l', category: 'other' },
      { name: 'Onion', quantity: '1', unit: 'large', category: 'produce' },
      { name: 'Butter', quantity: '3', unit: 'tbsp', category: 'dairy' },
      { name: 'Olive oil', quantity: '2', unit: 'tbsp', category: 'oils-fats' },
      { name: 'Thyme', quantity: '2', unit: 'sprigs', category: 'produce' },
    ],
  },
  {
    id: 'd-lemon-herb-chicken',
    name: 'Lemon Herb Roast Chicken',
    type: 'dinner',
    cuisine: 'American',
    dietTypes: ['non-veg'],
    prepTime: 15,
    cookTime: 50,
    servings: 4,
    description: 'Juicy roast chicken thighs with lemon, garlic, and fresh herbs over roasted vegetables',
    spiceLevel: 1,
    allergens: [],
    healthGoals: ['high-protein', 'muscle-gain', 'balanced', 'weight-loss'],
    nutrition: {
      macros: { calories: 510, protein: 44, carbs: 22, fat: 28, fiber: 4, sugar: 6 },
      micros: { vitaminA: 360, vitaminC: 48, vitaminD: 0.4, vitaminB12: 0.8, iron: 2.4, calcium: 60, potassium: 880, sodium: 360, zinc: 4.4, folate: 52, omega3: 120 },
    },
    ingredients: [
      { name: 'Chicken thighs (bone-in)', quantity: '8', unit: 'pieces', category: 'meat-seafood' },
      { name: 'Lemon', quantity: '2', unit: '', category: 'produce' },
      { name: 'Garlic', quantity: '6', unit: 'cloves', category: 'produce' },
      { name: 'Rosemary', quantity: '3', unit: 'sprigs', category: 'produce' },
      { name: 'Thyme', quantity: '3', unit: 'sprigs', category: 'produce' },
      { name: 'Baby potatoes', quantity: '400', unit: 'g', category: 'produce' },
      { name: 'Cherry tomatoes', quantity: '200', unit: 'g', category: 'produce' },
      { name: 'Olive oil', quantity: '4', unit: 'tbsp', category: 'oils-fats' },
    ],
  },
  {
    id: 'd-chole-bhature',
    name: 'Chole Bhature',
    type: 'dinner',
    cuisine: 'Indian',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    description: 'Spiced chickpea masala with fluffy deep-fried bread — a Punjabi classic',
    spiceLevel: 3,
    allergens: ['Gluten', 'Dairy'],
    healthGoals: ['balanced'],
    nutrition: {
      macros: { calories: 620, protein: 18, carbs: 86, fat: 22, fiber: 12, sugar: 8 },
      micros: { vitaminC: 16, iron: 5.6, calcium: 100, potassium: 720, magnesium: 80, sodium: 580, zinc: 2.8, folate: 160 },
    },
    ingredients: [
      { name: 'Chickpeas', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'All-purpose flour', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Onions', quantity: '3', unit: 'large', category: 'produce' },
      { name: 'Tomatoes', quantity: '4', unit: 'medium', category: 'produce' },
      { name: 'Yogurt', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { name: 'Chole masala', quantity: '2', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'Oil', quantity: '0.5', unit: 'cup', category: 'oils-fats' },
    ],
  },
  {
    id: 'd-teriyaki-chicken',
    name: 'Teriyaki Chicken Bowl',
    type: 'dinner',
    cuisine: 'Japanese',
    dietTypes: ['non-veg', 'pescatarian'],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    description: 'Glazed teriyaki chicken over steamed rice with pickled cucumbers and sesame seeds',
    spiceLevel: 1,
    allergens: ['Soy', 'Gluten', 'Sesame'],
    healthGoals: ['high-protein', 'balanced', 'muscle-gain'],
    nutrition: {
      macros: { calories: 490, protein: 38, carbs: 54, fat: 12, fiber: 3, sugar: 16 },
      micros: { vitaminA: 60, vitaminC: 8, vitaminD: 0.2, vitaminB12: 0.6, iron: 2.2, calcium: 80, potassium: 620, sodium: 820, zinc: 3.6, folate: 40, omega3: 120 },
    },
    ingredients: [
      { name: 'Chicken thighs', quantity: '600', unit: 'g', category: 'meat-seafood' },
      { name: 'Japanese rice', quantity: '2', unit: 'cups', category: 'grains-legumes' },
      { name: 'Soy sauce', quantity: '4', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'Mirin', quantity: '2', unit: 'tbsp', category: 'spices-condiments' },
      { name: 'Honey', quantity: '2', unit: 'tbsp', category: 'other' },
      { name: 'Sesame seeds', quantity: '2', unit: 'tbsp', category: 'other' },
      { name: 'Spring onions', quantity: '4', unit: '', category: 'produce' },
      { name: 'Cucumber', quantity: '1', unit: '', category: 'produce' },
    ],
  },

  // ── SNACKS ───────────────────────────────────────────────────
  {
    id: 's-fruit-nuts',
    name: 'Mixed Fruit & Nut Bowl',
    type: 'snack',
    cuisine: 'American',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian', 'non-veg'],
    prepTime: 2,
    cookTime: 0,
    servings: 1,
    description: 'Seasonal fruits with a handful of almonds, walnuts, and dark chocolate chips',
    spiceLevel: 1,
    allergens: ['Nuts'],
    healthGoals: ['weight-loss', 'balanced', 'heart-healthy'],
    nutrition: {
      macros: { calories: 220, protein: 6, carbs: 28, fat: 12, fiber: 4, sugar: 18 },
      micros: { vitaminC: 24, vitaminA: 4.0, iron: 1.2, calcium: 60, potassium: 380, magnesium: 48, folate: 20, omega3: 1200 },
    },
    ingredients: [
      { name: 'Mixed fruits', quantity: '1', unit: 'cup', category: 'produce' },
      { name: 'Mixed nuts', quantity: '30', unit: 'g', category: 'other' },
      { name: 'Dark chocolate chips', quantity: '1', unit: 'tbsp', category: 'other' },
    ],
  },
  {
    id: 's-hummus-veggies',
    name: 'Hummus with Veggie Sticks',
    type: 'snack',
    cuisine: 'Mediterranean',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian'],
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    description: 'Creamy homemade hummus with carrot, celery, and bell pepper sticks',
    spiceLevel: 1,
    allergens: ['Sesame'],
    healthGoals: ['weight-loss', 'balanced'],
    nutrition: {
      macros: { calories: 180, protein: 7, carbs: 22, fat: 8, fiber: 6, sugar: 6 },
      micros: { vitaminA: 480, vitaminC: 52, iron: 2.0, calcium: 60, potassium: 420, magnesium: 36, folate: 80 },
    },
    ingredients: [
      { name: 'Hummus', quantity: '6', unit: 'tbsp', category: 'other' },
      { name: 'Carrots', quantity: '2', unit: '', category: 'produce' },
      { name: 'Celery', quantity: '3', unit: 'stalks', category: 'produce' },
      { name: 'Bell peppers', quantity: '1', unit: '', category: 'produce' },
    ],
  },
  {
    id: 's-protein-smoothie',
    name: 'Protein Berry Smoothie',
    type: 'snack',
    cuisine: 'American',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    description: 'Greek yogurt blended with mixed berries, banana, and a spoonful of peanut butter',
    spiceLevel: 1,
    allergens: ['Dairy', 'Peanuts'],
    healthGoals: ['high-protein', 'muscle-gain', 'balanced'],
    nutrition: {
      macros: { calories: 300, protein: 20, carbs: 36, fat: 8, fiber: 5, sugar: 22 },
      micros: { vitaminC: 28, vitaminD: 0.4, vitaminB12: 1.0, iron: 1.4, calcium: 240, potassium: 580, sodium: 120, zinc: 1.6, folate: 32, omega3: 60 },
    },
    ingredients: [
      { name: 'Greek yogurt', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { name: 'Mixed frozen berries', quantity: '1', unit: 'cup', category: 'frozen' },
      { name: 'Banana', quantity: '0.5', unit: '', category: 'produce' },
      { name: 'Peanut butter', quantity: '1', unit: 'tbsp', category: 'other' },
      { name: 'Milk', quantity: '0.5', unit: 'cup', category: 'dairy' },
    ],
  },
  {
    id: 's-masala-chana',
    name: 'Masala Roasted Chana',
    type: 'snack',
    cuisine: 'Indian',
    dietTypes: ['veg', 'vegan', 'eggetarian', 'pescatarian', 'non-veg'],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    description: 'Crispy roasted chickpeas tossed with chaat masala, cumin, and lime',
    spiceLevel: 3,
    allergens: [],
    healthGoals: ['weight-loss', 'high-protein', 'balanced'],
    nutrition: {
      macros: { calories: 200, protein: 9, carbs: 30, fat: 4, fiber: 8, sugar: 2 },
      micros: { vitaminC: 4, iron: 2.8, calcium: 48, potassium: 340, magnesium: 44, folate: 100, sodium: 280, zinc: 1.6 },
    },
    ingredients: [
      { name: 'Chickpeas', quantity: '400', unit: 'g', category: 'canned' },
      { name: 'Chaat masala', quantity: '1', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Cumin powder', quantity: '0.5', unit: 'tsp', category: 'spices-condiments' },
      { name: 'Oil', quantity: '1', unit: 'tbsp', category: 'oils-fats' },
      { name: 'Lime', quantity: '0.5', unit: '', category: 'produce' },
    ],
  },
  {
    id: 's-cheese-apple',
    name: 'Apple & Cheese Slices',
    type: 'snack',
    cuisine: 'American',
    dietTypes: ['veg', 'eggetarian', 'pescatarian'],
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    description: 'Crisp apple slices paired with sharp cheddar and a drizzle of honey',
    spiceLevel: 1,
    allergens: ['Dairy'],
    healthGoals: ['balanced', 'heart-healthy'],
    nutrition: {
      macros: { calories: 200, protein: 7, carbs: 22, fat: 10, fiber: 3, sugar: 16 },
      micros: { vitaminA: 80, vitaminC: 6, vitaminD: 0.2, vitaminB12: 0.2, iron: 0.4, calcium: 220, potassium: 200, sodium: 160, zinc: 0.8 },
    },
    ingredients: [
      { name: 'Apple', quantity: '1', unit: 'medium', category: 'produce' },
      { name: 'Cheddar cheese', quantity: '40', unit: 'g', category: 'dairy' },
      { name: 'Honey', quantity: '1', unit: 'tsp', category: 'other' },
    ],
  },
]
