/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ['@nava-studios/catalog', '@nava-studios/ui'],
  async redirects() {
    return [
    { source: '/products/:slug', destination: '/', permanent: false },
    { source: '/work', destination: '/lab', permanent: false },
    { source: '/work/:slug', destination: '/lab/:slug', permanent: false },
    { source: '/gst-calculator', destination: 'http://localhost:3003', permanent: false },
    { source: '/gst-calculator/:path*', destination: 'http://localhost:3003/:path*', permanent: false },
    { source: '/tools/one-page-invoice', destination: 'http://localhost:3004', permanent: false },
    { source: '/tools/one-page-invoice/:path*', destination: 'http://localhost:3004/:path*', permanent: false },
    { source: '/tools/gst-whatsapp-biller', destination: 'http://localhost:3005', permanent: false },
    { source: '/tools/gst-whatsapp-biller/:path*', destination: 'http://localhost:3005/:path*', permanent: false },
    { source: '/tools/follow-up-fox', destination: 'http://localhost:3006', permanent: false },
    { source: '/tools/follow-up-fox/:path*', destination: 'http://localhost:3006/:path*', permanent: false },
    { source: '/tools/trade-quote', destination: 'http://localhost:3007', permanent: false },
    { source: '/tools/trade-quote/:path*', destination: 'http://localhost:3007/:path*', permanent: false },
    { source: '/tools/proposal-forge', destination: 'http://localhost:3008', permanent: false },
    { source: '/tools/proposal-forge/:path*', destination: 'http://localhost:3008/:path*', permanent: false },
    { source: '/tools/course-ship', destination: 'http://localhost:3009', permanent: false },
    { source: '/tools/course-ship/:path*', destination: 'http://localhost:3009/:path*', permanent: false },
    { source: '/tools/member-gate', destination: 'http://localhost:3010', permanent: false },
    { source: '/tools/member-gate/:path*', destination: 'http://localhost:3010/:path*', permanent: false },
    { source: '/tools/margin-lens', destination: 'http://localhost:3011', permanent: false },
    { source: '/tools/margin-lens/:path*', destination: 'http://localhost:3011/:path*', permanent: false },
    { source: '/tools/etsy-ledger', destination: 'http://localhost:3012', permanent: false },
    { source: '/tools/etsy-ledger/:path*', destination: 'http://localhost:3012/:path*', permanent: false },
    { source: '/tools/rent-ledger', destination: 'http://localhost:3013', permanent: false },
    { source: '/tools/rent-ledger/:path*', destination: 'http://localhost:3013/:path*', permanent: false },
    { source: '/tools/stock-sentinel', destination: 'http://localhost:3014', permanent: false },
    { source: '/tools/stock-sentinel/:path*', destination: 'http://localhost:3014/:path*', permanent: false },
    { source: '/tools/ship-watch', destination: 'http://localhost:3015', permanent: false },
    { source: '/tools/ship-watch/:path*', destination: 'http://localhost:3015/:path*', permanent: false },
    { source: '/tools/uptime-peek', destination: 'http://localhost:3016', permanent: false },
    { source: '/tools/uptime-peek/:path*', destination: 'http://localhost:3016/:path*', permanent: false },
    { source: '/tools/nudge-book', destination: 'http://localhost:3017', permanent: false },
    { source: '/tools/nudge-book/:path*', destination: 'http://localhost:3017/:path*', permanent: false },
    { source: '/tools/quote-card', destination: 'http://localhost:3018', permanent: false },
    { source: '/tools/quote-card/:path*', destination: 'http://localhost:3018/:path*', permanent: false },
    { source: '/tools/testimonial-jar', destination: 'http://localhost:3019', permanent: false },
    { source: '/tools/testimonial-jar/:path*', destination: 'http://localhost:3019/:path*', permanent: false },
    { source: '/tools/review-radar', destination: 'http://localhost:3020', permanent: false },
    { source: '/tools/review-radar/:path*', destination: 'http://localhost:3020/:path*', permanent: false },
    { source: '/tools/report-snap', destination: 'http://localhost:3021', permanent: false },
    { source: '/tools/report-snap/:path*', destination: 'http://localhost:3021/:path*', permanent: false },
    { source: '/tools/doc-chaser', destination: 'http://localhost:3022', permanent: false },
    { source: '/tools/doc-chaser/:path*', destination: 'http://localhost:3022/:path*', permanent: false },
    { source: '/tools/scope-guard', destination: 'http://localhost:3023', permanent: false },
    { source: '/tools/scope-guard/:path*', destination: 'http://localhost:3023/:path*', permanent: false },
    { source: '/tools/tiny-crm', destination: 'http://localhost:3024', permanent: false },
    { source: '/tools/tiny-crm/:path*', destination: 'http://localhost:3024/:path*', permanent: false },
    { source: '/tools/crew-board', destination: 'http://localhost:3025', permanent: false },
    { source: '/tools/crew-board/:path*', destination: 'http://localhost:3025/:path*', permanent: false },
    ]
  },
}

export default nextConfig
